version: '3'

services:
  mysql:
    image: mysql:8.0
    container_name: mysql_service
    env_file :
      - ./envs/mysqlenv
    volumes:
     - ./mysql-data/:/var/lib/mysql/
    command: mysqld --character-set-server=utf8 --collation-server=utf8_general_ci
    ports:
      - "3306:3306"

  backend:
    build: .
    container_name: backend
    volumes:
      - ./:/usr/src/account-book
    ports:
      - "8000:8000"
    links: 
      - "mysql:mysql"
    command: ["gunicorn","-b", "0.0.0.0:8000", "A.wsgi:application"]
    depends_on:
      - mysql
