# Generated by Django 3.2 on 2023-11-18 04:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='profile_image',
            field=models.CharField(default='images/basic_profile/account_profile_0.png', max_length=200),
        ),
    ]
