# Generated by Django 3.2 on 2023-12-09 16:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crawling', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='newsmodel',
            name='img_url',
            field=models.TextField(default=None, null=True),
        ),
    ]
