# Generated by Django 4.1.12 on 2023-10-26 06:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('instagram', '0002_comment'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Comment',
        ),
    ]
