# Generated by Django 3.2 on 2023-11-13 04:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('budget', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='accountdatemodel',
            name='datetime',
        ),
        migrations.AddField(
            model_name='accountdatemodel',
            name='date',
            field=models.DateField(default=None),
        ),
    ]
