# Generated by Django 3.2 on 2023-11-14 06:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('budget', '0002_auto_20231113_1330'),
    ]

    operations = [
        migrations.AlterField(
            model_name='accountdatedetailmodel',
            name='date',
            field=models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to='budget.accountdatemodel'),
        ),
    ]
