# Generated by Django 3.2 on 2023-11-15 01:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('budget', '0003_alter_accountdatedetailmodel_date'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='accountdatedetailmodel',
            options={'ordering': ['date', 'time']},
        ),
        migrations.AlterModelOptions(
            name='accountdatemodel',
            options={'ordering': ['-date']},
        ),
    ]
