# Generated by Django 3.2 on 2023-11-15 06:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('budget', '0004_auto_20231115_1016'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='accountdatedetailmodel',
            name='created_at',
        ),
        migrations.RemoveField(
            model_name='accountdatedetailmodel',
            name='updated_at',
        ),
        migrations.RemoveField(
            model_name='accountdatemodel',
            name='created_at',
        ),
        migrations.RemoveField(
            model_name='accountdatemodel',
            name='updated_at',
        ),
    ]
