# Generated by Django 3.2 on 2023-11-17 08:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('budget', '0005_auto_20231115_1534'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tagmodel',
            name='tag',
            field=models.CharField(max_length=10),
        ),
    ]
