# Generated by Django 3.2 on 2023-11-22 13:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('budget', '0006_alter_tagmodel_tag'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tagmodel',
            name='tag',
            field=models.CharField(blank=True, max_length=10),
        ),
    ]
