# Generated by Django 3.2 on 2023-11-30 13:13

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('budget', '0008_tagsummary'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='TagSummary',
            new_name='TagSummaryModel',
        ),
        migrations.RenameField(
            model_name='tagsummarymodel',
            old_name='incomde',
            new_name='income',
        ),
    ]
